# Generated by Django 3.1 on 2021-05-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
