# Generated by Django 3.1 on 2021-05-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20210521_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
